# Booking Service
spring.application.name=booking-service
server.port=8082

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/wheelconnect_booking?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# JWT
jwt.secret=${JWT_SECRET:WheelConnectSuperSecretKeyJWTTokenSigningForSecurity2026!!!}
jwt.issuer=WheelConnectIssuer
jwt.audience=WheelConnectAudience
jwt.expiration-hours=10

# Service Endpoints for REST Client / Feign
services.auth-service.url=${AUTH_SERVICE_URL:http://localhost:8081}
services.service-center-service.url=${SERVICE_CENTER_SERVICE_URL:http://localhost:8083}

# Logging
logging.level.root=INFO
logging.level.com.wheelconnect=DEBUG
